FROM alpine:latest

RUN apk --no-cache add \
    ca-certificates \
    tini

ADD build/bin/vpcnet-configure /bin/
ADD build/bin/vpcnet /cni/
ADD build/bin/loopback /cni/
ADD build/bin/bridge /cni/

ENTRYPOINT ["/sbin/tini", "--", "vpcnet-configure"]
